spring:
  datasource:
    url: jdbc:h2:file:./data/posgateway
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.posgateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

terminal:
  port: COM3
  baudRate: 9600
  timeout: 5000

security:
  encryption:
    key: your-encryption-key
    algorithm: AES/CBC/PKCS5Padding
